/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  ArticleCheckResult,  ArticleGenerationResult,  ArticleGenerationTool,  ArticleMemorySaveEvent,  ArticleOptimizeResult,  EventMessage,  MemoryRetrivalTool,  MemoryStateToolData,  RequestHumanForConfirmation,  RequestHumanForSatisfaction,  Resume,  RuleSet,  StopEvent } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface ArticleCheckResult {
        title?: (string | null)
        markdownContent?: (string | null)
    }
    
    export interface ArticleGenerationResult {
        title?: (string | null)
        markdownContent?: (string | null)
        articleType?: (string | null)
    }
    
    /**
 * 文章初步生成工具
 */
    export interface ArticleGenerationTool {
        event: "tool"
        data: "ArticleGenerationTool"
    }
    
    export interface ArticleMemorySaveEvent {
        event: "memory_saved"
        data: "memory_data"
    }
    
    export interface ArticleOptimizeResult {
        title?: (string | null)
        markdownContent?: (string | null)
        articleType?: (string | null)
    }
    
    export interface EventMessage {
        eventName?: (string | null)
        dataContent?: (string | null)
    }
    
    export interface MemoryRetrivalTool {
        event: "tool"
    }
    
    /**
 * 对于比较长的上下文记忆，需要通过 MemoryStateToolData 工具去获取相应的记忆
 */
    export interface MemoryStateToolData {
        toolName?: (string | null)
        dataContent?: (string | null)
    }
    
    /**
 * 让用户确认任务是否完成
 */
    export interface RequestHumanForConfirmation {
        event: "request_human"
        data: "isTaskFinished"
    }
    
    /**
 * 让用户确认当前生成的内容是否满足需求
 */
    export interface RequestHumanForSatisfaction {
        event: "request_human"
        data: "isSatisfaction?"
    }
    
    export interface Resume {
        name?: (string | null)
        email?: (string | null)
        experience?: (string | null)[]
        skills?: (string | null)[]
    }
    
    export interface RuleSet {
        content?: (string | null)
    }
    
    export interface StopEvent {
        event: "stop"
        data: ((null | null) | null)
    }
    
}